librespeed/speedtest

example2.html, example3.html, example4.html, garbage.php, speedtest_worker.js
Hi Federico,
thanks for your great script, I adopted it for our internal end user speedtest in the school network.
I published our internally used interface as new example. It uses some beatiful gauges by justgage.js for nice displays, and Google Fonts for more awesomeness. The example only uses online CDNs, so no additional dependencies in the repo.
Additionally, I changed garbage.php a bit, now enforcing download (good for comparisons of measured speed vs. raw download speed while developing) and disabling php buffering stuff. That seemed to improve measurement stability and accuracy for us.
Feel free to merge - or not to :-) 
Martin
=> New example, "improved" garbage.php

getIP.php
getIP({"ip":"8.8.8.8"});
Used to show client IP on speed test page.
=> Outputs Client IP in JSON

telemetry.php
The ability to select sqlite as a data source, it is desirable to put the catalog above the web or to forbid downloading
----------
Возможность выбора sqlite в качестве бызы данных, желательно поместить каталогом выше веб или запретить скачивание
=> New type of database sqlite

doc.md, telemetry.php, telemetry_settings.php
=> CSV support for telemetry

src/SpeedTest.js
Effectively solve the problem of excessive memory usage of nodejs. Originally, it may need to allocate 100M of memory. Now only allocate 1M memory and reuse it.
=> fix #200 Solve memory usage

Dockerfile
=> Montée de version PHP

README.md, package.json, src/SpeedTest.js, src/public/example-multipleServers-pretty.html
Fixed node.js version to work as backend for multiple test points mode.
Added example of index.html to configure multiple points mode with node.js frontend.
=> (Node.js port) Added possibility to act as frontend and backend in Multiple test points mode

config/config.go, settings.toml, web/helpers.go
- Added ServerLat & ServerLng to config
- Returning the values from config if they greater than 0
=> Make Server-Location configurable

speedtest_worker.js
=> use delay in ultest

results/index.php, results/stats.php, results/telemetry.php, results/telemetry_settings.php
Added option for port number for MySQL connection to allow use in non-standard installs
=> Add Port option for MySQL

docker/entrypoint.sh
=> Fix #334 wrong port config generated

speedtest.js
=> fixes onend()

backend/empty.php, backend/garbage.php, backend/getIP.php, backend/getIP_ipInfo_apikey.php
A friend told me about the librespeed project and about this repo when I asked if he knew any repos that I might be able to work on during hacktoberfest :)
When I started to look at the code, I noticed that a little bit of refactoring might help to make the code a bit easier to understand for someone who is new to the codebase. I then tried to find out what the different parts of the code do and I then moved those parts into separate functions. In the end I think the code is now easier to understand for someone who is not already very familiar with it, so I hope it will also help future contributors.
I noticed that in the readme it says that the code still runs with PHP 5.4, so I tried not to introduce any BC breaks by using any new syntax or PHP functions, so this PR does not alter the …
=> Refactor backend PHP code

example-multipleServers-full.html, example-singleServer-full.html
Fixes #363 
In comparison to the screenshot provided in the issue, here is a screenshot with the fixes in this PR:
Tested with Firefox and Chromium.
=> Fix privacy link width

Dockerfile, docker/entrypoint.sh
Following up on #219, add favicon to docker image
=> Add favicon.ico

backend/garbage.php
https://www.php.net/random_bytes
=> Use `random_bytes` when available

Dockerfile
Updated to use php8.2-apache as the upstream image for Docker
=> Updated Docker to use php8.2-apache as the upstream image.

doc_docker.md
This should make it easier to quickly spin-up a container.
=> Add basic docker compose example

Dockerfile
Kind of Dockerfile best practices 🤩 
Image size change as below:
```
REPOSITORY          TAG                  IMAGE ID       CREATED          SIZE
after               latest               de7531413c1e   6 minutes ago    463MB
before              latest               f2756a4fd85a   12 minutes ago   481MB
```
=> Clean up apt lists after installation in Dockerfile

README.md
=> Link to docker documentation

Dockerfile, doc.md, speedtest.js, speedtest_worker.js
Hi ! 
This PR just fixes some typos and line break consistency in Dockerfile
=> Fix some typos and formatting

README.md
Hi there!
This is just a small accessibility improvement for the GIF in the Readme.
=> Add descriptive alt-text to GIF in Readme

doc.md, docker/frontend.php, docker/standalone.php, example-multipleServers-full.html, example-multipleServers-pretty.html, example-singleServer-customSettings.html, example-singleServer-full.html, example-singleServer-gauges.html, example-singleServer-pretty.html, example-singleServer-progressBar.html, results/index.php, speedtest.js
=> switch units to Mbit/s

backend/getIP.php
Added regex to backend/getIP.php function getLocalOrPrivateIpInfo() to match RFC 4193 Unique Local IPv6 Unicast Addresses
=> Added IPv6 ULA regex match

README.md
Mention the CLI client in the Readme for better visibility.
=> Mention CLI client in Readme

.github/workflows/docker-publish.yml
=> add on publish trigger

speedtest.js, speedtest_worker.js
Changed var to let/const because it's completely supported by IE11 and all other browsers since 2015.
=> Using of the modern JS

index.html
=> Added dark style for the <select> HTML property

examples/example-singleServer-modern.html
Added an example of a very simple and modern design
=> Added a modern design example
