- garbage.php
Normalize quotes and avoid DOS with gigant ckSize values
> Avoid DOS with gigant ckSize values

- doc.md
- telemetry.php
- telemetry_settings.php
I've added postgresql database support for telemetry, using PDO similar to the way sqlite3 support was implemented. I moved all database related settings into a separate file so people don't have to modify telemetry.php in order to get everything set up. Updated related documentation.
> Added postgresql db support to telemetry

- telemetry_postgresql.sql
Not sure how the extra `d` character made it in there, but it causes failures while building the database schema, which in turn breaks storing telemetry results. I've double checked everything works with this change.
> Fixed postgresql schema typo

- getIP.php
If the speedtest is behind a reverse proxy that is used as an IPv6 endpoint but the PHP is interpreted on an IPv4 server, the forwarded-for header is in an IPv6-mapped IPv4 format (`::ffff:X.Y.Z.W`)
This strips the `::ffff:` part so ipinfo.io can return the correct informations.
> Remove prefix on IPv6-mapped IPv4

- getIP.php
Reformating and indenting
+ avoid requesting ipinfo.io and generating a php error when the connection is from localhost.
Also notice some http proxy may add a false HTTP_X_FORWARDED_FOR
> Avoid requesting ipinfo.io when the connection is from localhost

- results/index.php
Postgres and SQLite were referencing the wrong variable causing the jitter field to always be empty.
> Fix results image for jitter

- getIP.php
When there are multiple proxies, the `X-Forwarded-For` header will be a [comma-separated list](https://en.wikipedia.org/wiki/X-Forwarded-For#Format) of IPs, with the original client first in the list. This change strips the first comma and everything after it, to keep only the client IP.
> Handle X-Forwarded-For with multiple hosts

- getIP.php
Fixed improper reporting of IPV6 and IPV4 localhost addresses, more detailed explanation in comments of modified file.
Basically, 
for ipv6: the only possible localhost ipv6 is ::1, not any string that contains ::1 like you were doing before.
for ipv4: any ip in the 127/8 range (from 127.0.0.1 to 127.255.255.254), is a localhost ipv4 address. not just 127.0.0.1 like you were doing before.
edit: commit says 254.254.254, the code is still fine for the correct implementation, it is just checking for prefix 127. which is any ip in 127/8 range, as required.
> Fixing improper localhost address reporting for ipv4 and v6

- speedtest_worker.js
Tell PHP not to parse the random data that's POST'ed during upload tests.
The full error logged is `PHP message: PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini.`.
> Fix error "Input variables exceeded 1000"

- docker/entrypoint.sh
`docker/entrypoint.sh` currently expects `$ENABLE_ID_OBFUSCATION` and `$REDACT_IP_ADDRESSES` to be double-quoted strings but they are booleans. This PR resolves the issue by removing the quotes in the regular expressions.
> Fix telemetry variables in Docker entrypoint

- backend/getIP.php
Fixes #306 
I don't have some proxy or something at hand which would set this header, but I tested the change with curl.
Before this change:
```
$ curl http://my-deployment-of-librespeed/backend/getIP.php -H 'X-Real-IP: foobar'
{"processedString":"<MY_IP>","rawIspInfo":""}
```
After this change:
```
$ curl http://my-deployment-of-librespeed/backend/getIP.php -H 'X-Real-IP: foobar'
{"processedString":"foobar","rawIspInfo":""}
```
> Fix check for X-Real-IP header when trying to find the correct client IP

- backend/getIP.php
- doc.md
- results/idObfuscation.php
- results/index.php
- results/stats.php
- results/telemetry.php
- results/telemetry_db.php
- results/telemetry_settings.php
This is a follow up to #362 refactoring the rest of the PHP code trying to improve readability. As you seemed quite happy with the other PR #362 I thought I'd give the other PHP files a try, too.
Reading from/writing into the database is now handled in a separate file `telemetry_db.php`. I wasn't sure about the file naming conventions in this repo, so please just let me know if the file should be renamed. All three possible database types now use PDO and the only difference left is the instantiation of the PDO object. I also tested the changes with all three database types.
I had a hard time splitting the code for the image generation into smaller functions so I at least tried to add comments explaining what the code does.
The scripts did just `die()` on most errors before. I kept that …
> Refactor `results/` PHP code

- docker/entrypoint.sh
Check for $DB_TYPE of  `mysql` or `postgresql` and replace the telemetry settings as needed. The db type of `sqlite` will remain the fallback case if neither of the first 2 types are used.
> Add mysql and postgresql settings to docker entrypoint

- backend/getIP.php
- backend/getIP_util.php
- results/telemetry.php
Similar to PR #436, but I moved and re-used the existing `getClientIp()` function so it can be called from `telemetry.php` when storing the IP address to the database. This allows for the correct IP address to be stored in IP field when behind a proxy.
> Save correct IP address to database

- README.md
- results/sanitycheck.php
- results/telemetry_db.php
- results/telemetry_mssql.sql
- results/telemetry_settings.php
I have added support for using Microsoft SQL Server to host the speedtest database.  
To help with debugging DB connectivity issues, I also created a Sanity Check page which checks if required PHP extensions are installed, and that the website can connect to the database.
> Microsoft SQL Server support and Sanity Check page

- .github/workflows/docker-publish.yml
- README.md
- doc_docker.md
for better integration with the source-code and reducing complexity
> Switch docker repo from docker-hub to github packages

- Dockerfile
- docker/entrypoint.sh
Currently we're directly starting apache2 from within the entrypoint script. This has some unintended side effects:
```sh
docker top speedtest
```
```
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                18397               18367               0                   20:22               ?                   00:00:00            bash /entrypoint.sh
root                18626               18397               0                   20:22               ?                   00:00:00            apache2 -DFOREGROUND
www-data            18726               18626               0                   20:22               ?                   00:00:00            apache2 -DFOREGROUND
www-data …
```
> Start apache with exec

- backend/garbage.php
Reverting this commit fixed #613 for me. Tested with my own build `ghcr.io/zypa13510/librespeed`.
I'm not exactly sure why, not a PHP expert, but my guess is that the `random_byte()` call could be using CSPRNG which is slower. If that is the case, I believe it is perfectly fine to not use CSPRNG, as this is just a speed test not a password generator.
Revert: fa0ac8cd2336052286cd3556889449660e4d9c83, #487
Close: #613
> fix: download speed is 0 on certain platform

- .github/workflows/docker-publish.yml
- Dockerfile
- Dockerfile.alpine
- docker/entrypoint.sh
The alpine based php docker image results in a 5x reduction in image size when compared with the debian one (~125MB vs ~540MB)
> Add alpine docker image version

- backend/getIP.php
This patch is returns the ability to do online check for IP location on older PHP versions.
> fix ipinfo-db with old versions of PHP

- doc_docker.md
Due to recent changes in #678, the app now listens on port 8080 by default, so I updated the docker documentation to prevent confusion.
Also note it was a breaking change and I noticed it only because of another user's complaint.
> Update docker documentation
